// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmZkp_IDHiCrDYxvabCPM0S87HW6HqNBA',
    appId: '1:53492629489:web:16fc40200399c43981ce50',
    messagingSenderId: '53492629489',
    projectId: 'walid-project-60fee',
    authDomain: 'walid-project-60fee.firebaseapp.com',
    storageBucket: 'walid-project-60fee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfuEPX7D-9iszwKLtL84_tIXgEnYVuxwg',
    appId: '1:53492629489:android:6b206a5f403f24a481ce50',
    messagingSenderId: '53492629489',
    projectId: 'walid-project-60fee',
    storageBucket: 'walid-project-60fee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6RK8CkVpW0YG3pMCrlcqm4youL1yqWCU',
    appId: '1:53492629489:ios:aa4473f8ddeba2ab81ce50',
    messagingSenderId: '53492629489',
    projectId: 'walid-project-60fee',
    storageBucket: 'walid-project-60fee.appspot.com',
    iosBundleId: 'com.example.walidProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6RK8CkVpW0YG3pMCrlcqm4youL1yqWCU',
    appId: '1:53492629489:ios:aa4473f8ddeba2ab81ce50',
    messagingSenderId: '53492629489',
    projectId: 'walid-project-60fee',
    storageBucket: 'walid-project-60fee.appspot.com',
    iosBundleId: 'com.example.walidProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmZkp_IDHiCrDYxvabCPM0S87HW6HqNBA',
    appId: '1:53492629489:web:15b3aa8c4a86fda781ce50',
    messagingSenderId: '53492629489',
    projectId: 'walid-project-60fee',
    authDomain: 'walid-project-60fee.firebaseapp.com',
    storageBucket: 'walid-project-60fee.appspot.com',
  );
}
